# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: get ffmpeg
        run: |
          powershell -c "Invoke-WebRequest -Uri https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -OutFile ffmpeg.zip
          unzip ffmpeg.zip

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          .\ahk2exe.exe compile.ahk
            - name: Upload a Build Artifact
            
      - uses: actions/upload-artifact@v4.2.0
        with:
          # Artifact name
          name: upload
          # A file, directory or wildcard pattern that describes what to upload
          path: flicflac.exe
          # The desired behavior if no files are found using the provided path.
