# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: windows
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: make
        run: |
          git clone --recursive https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          make config
          echo configured
          make install
          echo made
          cp -r *.exe ..
          cp -r */*.exe ..
          echo copied
          cd ..
          .\ahk2exe.exe compile.ahk
          echo done
          
      - name: Upload a Build Artifact      
        uses: actions/upload-artifact@v4.2.0
        with:
          # Artifact name
          name: upload
          # A file, directory or wildcard pattern that describes what to upload
          path: flicflac.exe
          # The desired behavior if no files are found using the provided path.
